Product:
    type: entity
    table: product
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        name:
            type: string
            nullable: false
            length: 33
            options:
                fixed: false
        description:
            type: string
            nullable: false
            length: 24
            options:
                fixed: false
        price:
            type: decimal
            nullable: false
            precision: 3
            scale: 1
        category:
            type: string
            nullable: false
            length: 5
            options:
                fixed: false
        image:
            type: string
            nullable: false
            length: 133
            options:
                fixed: false
        summary:
            type: string
            nullable: false
            length: 397
            options:
                fixed: false
    lifecycleCallbacks: {  }
